"""
Generate physics reference sheet PDF
"""
import os
from pathlib import Path


def generate_physics_pdf(output_path: str):
    """
    Generate Kelly physics reference sheet as PDF.
    
    Args:
        output_path: Output PDF path
    """
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.units import inch
        from reportlab.pdfgen import canvas
        from reportlab.lib import colors
        
        # Create canvas
        c = canvas.Canvas(output_path, pagesize=letter)
        width, height = letter
        
        # Title
        c.setFont("Helvetica-Bold", 24)
        c.drawString(1 * inch, height - 1 * inch, "Kelly Physics Reference")
        
        # Subtitle
        c.setFont("Helvetica", 12)
        c.setFillColor(colors.grey)
        c.drawString(1 * inch, height - 1.3 * inch, "Director's Chair & Hair Physics for iClone")
        
        # Content
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 14)
        y = height - 2 * inch
        
        sections = [
            ("Chair Frame (Wood)", [
                "Type: Rigid Body",
                "Density: 700 kg/m³",
                "Restitution: 0.1",
                "Friction: 0.6"
            ]),
            ("Seat/Back Fabric", [
                "Type: Soft Cloth",
                "Stiffness: 0.85",
                "Damping: 0.30",
                "Gravity: -9.8 m/s²",
                "Pinning: Seat edges at frame; back fabric top edge"
            ]),
            ("Elbows/Wrists", [
                "Type: Reach Targets",
                "Enabled: ON",
                "Compression: 0.5–1.5 cm"
            ]),
            ("Hair", [
                "Type: Spring Chain",
                "Gravity: -9.8 m/s²",
                "Damping: 2.2",
                "Wind: 0.3 m/s"
            ]),
            ("Camera Setup", [
                "Focal Length: 35 mm",
                "Resolution: 7680×4320 (8K)",
                "Color Space: sRGB"
            ])
        ]
        
        for title, items in sections:
            c.setFont("Helvetica-Bold", 12)
            c.drawString(1 * inch, y, title)
            y -= 0.25 * inch
            
            c.setFont("Helvetica", 10)
            for item in items:
                c.drawString(1.2 * inch, y, "• " + item)
                y -= 0.2 * inch
            
            y -= 0.2 * inch
        
        # Footer
        c.setFont("Helvetica-Oblique", 9)
        c.setFillColor(colors.grey)
        c.drawString(1 * inch, 0.5 * inch, "Generated by Kelly Asset Pack Generator v1.0")
        
        c.save()
        print(f"Saved: {output_path}")
        
    except ImportError:
        print("Warning: reportlab not installed, generating PNG reference instead")
        generate_physics_png(output_path.replace(".pdf", ".png"))


def generate_physics_png(output_path: str):
    """
    Generate physics reference as PNG (fallback).
    
    Args:
        output_path: Output PNG path
    """
    try:
        import matplotlib.pyplot as plt
        import matplotlib.patches as mpatches
        
        fig, ax = plt.subplots(figsize=(8.5, 11))
        ax.axis("off")
        
        # Title
        ax.text(0.5, 0.95, "Kelly Physics Reference", 
                ha="center", va="top", fontsize=20, fontweight="bold")
        ax.text(0.5, 0.92, "Director's Chair & Hair Physics for iClone",
                ha="center", va="top", fontsize=10, color="gray")
        
        # Content
        sections = [
            ("Chair Frame (Wood)", [
                "Type: Rigid Body",
                "Density: 700 kg/m³",
                "Restitution: 0.1",
                "Friction: 0.6"
            ]),
            ("Seat/Back Fabric", [
                "Type: Soft Cloth",
                "Stiffness: 0.85",
                "Damping: 0.30",
                "Gravity: -9.8 m/s²",
                "Pinning: Seat edges at frame; back fabric top edge"
            ]),
            ("Elbows/Wrists", [
                "Type: Reach Targets",
                "Enabled: ON",
                "Compression: 0.5–1.5 cm"
            ]),
            ("Hair", [
                "Type: Spring Chain",
                "Gravity: -9.8 m/s²",
                "Damping: 2.2",
                "Wind: 0.3 m/s"
            ]),
            ("Camera Setup", [
                "Focal Length: 35 mm",
                "Resolution: 7680×4320 (8K)",
                "Color Space: sRGB"
            ])
        ]
        
        y = 0.85
        for title, items in sections:
            ax.text(0.1, y, title, fontsize=12, fontweight="bold")
            y -= 0.03
            
            for item in items:
                ax.text(0.15, y, "• " + item, fontsize=9)
                y -= 0.025
            
            y -= 0.02
        
        # Footer
        ax.text(0.5, 0.02, "Generated by Kelly Asset Pack Generator v1.0",
                ha="center", fontsize=8, style="italic", color="gray")
        
        plt.tight_layout()
        plt.savefig(output_path, dpi=300, bbox_inches="tight")
        plt.close()
        
        print(f"Saved: {output_path}")
        
    except Exception as e:
        print(f"Warning: Could not generate physics reference: {e}")


