#!/usr/bin/env npx tsx
/**
 * 📤 UPLOAD INFOGRAPHICS FOR A DAY TO SUPABASE (CANONICAL PIPELINE)
 *
 * Promotes locally generated infographic PNGs from the unified factory
 * into Supabase Storage + lesson_assets, and wires lesson_atoms.visual_url.
 *
 * Canonical shape (for now, EN-only, no age-buckets):
 *   - Bucket: lesson-visuals
 *   - Path:   lesson-visuals/day-XYZ/infographics/{hook|fact1|fact2|fact3|wisdom}.png
 *
 * Usage:
 *   # Day 1 using architect as source (default)
 *   npx tsx scripts/lesson-factory/upload-day1-infographics.ts
 *
 *   # Explicit day and source archetype folder (e.g., explorer)
 *   npx tsx scripts/lesson-factory/upload-day1-infographics.ts --day 7 --source archetype-folder-name
 */

import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';

// =============================================================================
// TYPES & CONSTANTS
// =============================================================================

const DEFAULT_DAY = 1;

const PHASES = ['Hook', 'Fact1', 'Fact2', 'Fact3', 'Wisdom'] as const;
type PhaseName = (typeof PHASES)[number];

// We pick ONE archetype's infographics as the canonical SEED visuals.
// Architect is stable and already fully generated by the unified factory for Day 1.
// For other days you can pass --source to point at a different archetype folder.
const DEFAULT_SOURCE_ARCHETYPE_PATH = 'architect';

const CONFIG = {
  SUPABASE_URL: process.env.PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL!,
  SUPABASE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY!,
  BUCKET_NAME: 'lesson-visuals',
};

if (!CONFIG.SUPABASE_URL || !CONFIG.SUPABASE_KEY) {
  // eslint-disable-next-line no-console
  console.error('❌ Missing Supabase credentials (PUBLIC_SUPABASE_URL / SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)');
  process.exit(1);
}

const supabase = createClient(CONFIG.SUPABASE_URL, CONFIG.SUPABASE_KEY);

// =============================================================================
// HELPERS
// =============================================================================

function phaseToFilename(phase: PhaseName): string {
  return phase.toLowerCase() + '.png';
}

function phaseToVariantName(phase: PhaseName): string {
  // Store lowercase in lesson_assets.variant_name for easier querying
  return phase.toLowerCase();
}

function buildStoragePath(dayNumber: number, phase: PhaseName): string {
  const dayStr = String(dayNumber).padStart(3, '0');
  return `day-${dayStr}/infographics/${phase.toLowerCase()}.png`;
}

async function getCoreLessonId(dayNumber: number): Promise<string> {
  const { data, error } = await supabase
    .from('core_lessons')
    .select('id')
    .eq('day_number', dayNumber)
    .single();

  if (error || !data) {
    throw new Error(`Core lesson not found for day ${dayNumber}: ${error?.message ?? 'no data'}`);
  }

  return data.id as string;
}

async function uploadInfographicForPhase(
  coreLessonId: string,
  phase: PhaseName,
  dayNumber: number,
  localRoot: string,
  sourceArchetypePath: string
): Promise<{ phase: PhaseName; ok: boolean; message?: string }> {
  const filename = phaseToFilename(phase);
  const localPath = path.join(localRoot, filename);

  if (!fs.existsSync(localPath)) {
    return { phase, ok: false, message: `Local file missing: ${localPath}` };
  }

  const fileBuffer = fs.readFileSync(localPath);
  const fileSizeMb = (fileBuffer.length / 1024 / 1024).toFixed(2);
  const storagePath = buildStoragePath(dayNumber, phase);

  console.log(`\n📄 Phase: ${phase}`);
  console.log(`   📁 Local:   ${localPath}`);
  console.log(`   ☁️ Storage: ${CONFIG.BUCKET_NAME}/${storagePath}`);
  console.log(`   📦 Size:    ${fileSizeMb} MB`);

  // Upload to Supabase Storage with upsert
  const { error: uploadError } = await supabase.storage
    .from(CONFIG.BUCKET_NAME)
    .upload(storagePath, fileBuffer, {
      contentType: 'image/png',
      upsert: true,
    });

  if (uploadError) {
    console.error(`   ❌ Upload failed: ${uploadError.message}`);
    return { phase, ok: false, message: uploadError.message };
  }

  const { data: urlData } = supabase.storage.from(CONFIG.BUCKET_NAME).getPublicUrl(storagePath);
  const publicUrl = urlData.publicUrl as string;

  console.log(`   ✅ Uploaded: ${publicUrl}`);

  // Upsert into lesson_assets
  const variantName = phaseToVariantName(phase);

  const { data: existing, error: existingError } = await supabase
    .from('lesson_assets')
    .select('id')
    .eq('lesson_id', coreLessonId)
    .eq('asset_type', 'image')
    .eq('asset_subtype', 'infographic')
    .eq('variant_name', variantName)
    .maybeSingle();

  if (existingError && existingError.code !== 'PGRST116') {
    console.error(`   ❌ Failed to check existing lesson_assets: ${existingError.message}`);
    return { phase, ok: false, message: existingError.message };
  }

  const payload = {
    lesson_id: coreLessonId,
    asset_type: 'image',
    asset_subtype: 'infographic',
    variant_name: variantName,
    storage_provider: 'supabase',
    storage_path: storagePath,
    public_url: publicUrl,
    cdn_url: publicUrl,
    generator: 'unified-factory',
    model_version: 'v1',
    generation_params: {
      day_number: dayNumber,
      phase,
      source_archetype_path: sourceArchetypePath,
    },
    is_approved: true,
  };

  if (existing?.id) {
    const { error: updateError } = await supabase
      .from('lesson_assets')
      .update(payload)
      .eq('id', existing.id);

    if (updateError) {
      console.error(`   ❌ lesson_assets update failed: ${updateError.message}`);
      return { phase, ok: false, message: updateError.message };
    }

    console.log('   📝 lesson_assets updated (upsert)');
  } else {
    const { error: insertError } = await supabase.from('lesson_assets').insert(payload);

    if (insertError) {
      console.error(`   ❌ lesson_assets insert failed: ${insertError.message}`);
      return { phase, ok: false, message: insertError.message };
    }

    console.log('   📝 lesson_assets inserted');
  }

  // Also wire lesson_atoms.visual_url for all atoms for this day/phase
  const { error: atomUpdateError } = await supabase
    .from('lesson_atoms')
    .update({ visual_url: publicUrl })
    .eq('core_lesson_id', coreLessonId)
    .eq('phase', phase);

  if (atomUpdateError) {
    console.error(`   ⚠️ lesson_atoms visual_url update failed: ${atomUpdateError.message}`);
  } else {
    console.log('   🔗 lesson_atoms.visual_url updated for this phase');
  }

  return { phase, ok: true };
}

// =============================================================================
// MAIN
// =============================================================================

async function main() {
  console.log('═'.repeat(74));
  console.log('📤 UPLOAD INFOGRAPHICS TO SUPABASE (CANONICAL PROMOTION)');
  console.log('═'.repeat(74));

  // ---------------------------------------------------------------------------
  // CLI args
  // ---------------------------------------------------------------------------
  const args = process.argv.slice(2);
  let dayNumber = DEFAULT_DAY;
  let sourceArchetypePath = DEFAULT_SOURCE_ARCHETYPE_PATH;

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--day') {
      const value = args[i + 1];
      if (!value) {
        console.error('❌ Missing value for --day');
        process.exit(1);
      }
      dayNumber = Number.parseInt(value, 10);
      i++;
    } else if (arg === '--source') {
      const value = args[i + 1];
      if (!value) {
        console.error('❌ Missing value for --source');
        process.exit(1);
      }
      sourceArchetypePath = value;
      i++;
    }
  }

  const dayStr = String(dayNumber).padStart(3, '0');
  const localRoot = path.join(
    process.cwd(),
    'generated-assets',
    'unified-factory',
    `day-${dayStr}`,
    sourceArchetypePath,
    'infographics'
  );

  console.log(`\n📅 Day: ${dayNumber}`);
  console.log(`🧩 Source archetype path: ${sourceArchetypePath}`);
  console.log(`📂 Local root: ${localRoot}\n`);

  if (!fs.existsSync(localRoot)) {
    console.error(`❌ Local infographic directory not found: ${localRoot}`);
    console.error('   Run the unified lesson factory for this day/archetype first.');
    process.exit(1);
  }

  const coreLessonId = await getCoreLessonId(dayNumber);
  console.log(`✅ core_lessons.id for Day ${dayNumber}: ${coreLessonId}\n`);

  const results: { phase: PhaseName; ok: boolean; message?: string }[] = [];

  for (const phase of PHASES) {
    // eslint-disable-next-line no-await-in-loop
    const res = await uploadInfographicForPhase(coreLessonId, phase, dayNumber, localRoot, sourceArchetypePath);
    results.push(res);
  }

  console.log('\n' + '-'.repeat(74));
  const successCount = results.filter(r => r.ok).length;
  const failCount = results.length - successCount;
  console.log(`📊 Summary: ${successCount} succeeded, ${failCount} failed`);

  for (const r of results) {
    if (r.ok) {
      console.log(`   ✅ ${r.phase}`);
    } else {
      console.log(`   ❌ ${r.phase} – ${r.message ?? 'unknown error'}`);
    }
  }

  console.log('-'.repeat(74));

  if (failCount > 0) {
    process.exit(1);
  }
}

// eslint-disable-next-line unicorn/prefer-top-level-await
main().catch(err => {
  // eslint-disable-next-line no-console
  console.error('❌ Unexpected error in upload-day1-infographics:', err);
  process.exit(1);
});


