steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$CLOUD_RUN_SERVICE:$COMMIT_SHA",
        "-f",
        "deployment/cloudrun/Dockerfile",
        ".",
      ]
images:
  - "gcr.io/$PROJECT_ID/$CLOUD_RUN_SERVICE:$COMMIT_SHA"

