#!/usr/bin/env npx tsx
/**
 * GENERATE CLIFF AND OUTRO ATOMS
 * 
 * Fills the gap for missing Cliff and Outro phases in lesson_atoms.
 * These phases were not being generated by the main atom generation pipeline.
 * 
 * Usage:
 *   npx tsx scripts/generate-cliff-outro-atoms.ts --day=17
 *   npx tsx scripts/generate-cliff-outro-atoms.ts --all-days
 *   npx tsx scripts/generate-cliff-outro-atoms.ts --day=17 --dry-run
 */

import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL!;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

// All 10 archetypes (with "The " prefix to match existing data)
const ARCHETYPES = [
  'The Scientist',
  'The Explorer', 
  'The Rebel',
  'The Architect',
  'The Diplomat',
  'The Empath',
  'The MacGyver',
  'The Mystic',
  'The Provider',
  'The Storyteller',
  'The Strategist',
  'The Survivor',
] as const;

type Archetype = typeof ARCHETYPES[number];

// Archetype-specific cliff and outro content
const ARCHETYPE_CONTENT: Record<Archetype, { cliff: CliffContent; outro: OutroContent }> = {
  'The Scientist': {
    cliff: {
      script: "Now here's where it gets interesting - you have a choice. Would you like to explore this through data and evidence, or through experimentation and discovery? Both paths lead to understanding, but the journey is different.",
      prompt: "How do you want to explore?",
      optionA: { label: "Show me the data", icon: "📊" },
      optionB: { label: "Let me experiment", icon: "🔬" },
    },
    outro: {
      script: "And there you have it! You've just added a new piece to your understanding. I love how you approached this with curiosity. Tomorrow, we'll build on what you've learned. Keep questioning everything!",
    },
  },
  'The Explorer': {
    cliff: {
      script: "Alright, adventurer! Two paths stretch before you. Do you want to take the scenic route and discover hidden connections, or blaze straight to the destination? Either way leads to treasure.",
      prompt: "Which adventure calls to you?",
      optionA: { label: "Scenic discovery", icon: "🗺️" },
      optionB: { label: "Direct path", icon: "🧭" },
    },
    outro: {
      script: "What a journey we've been on today! You've explored new territory and discovered something wonderful. Tomorrow brings new horizons. Rest up, explorer - more adventures await!",
    },
  },
  'The Rebel': {
    cliff: {
      script: "Here's the thing - you don't have to do this the conventional way. You could challenge the accepted wisdom, or you could work within the system to change it. Both are valid forms of rebellion.",
      prompt: "How will you shake things up?",
      optionA: { label: "Challenge it", icon: "⚡" },
      optionB: { label: "Transform it", icon: "🔄" },
    },
    outro: {
      script: "Now that's what I call thinking for yourself! You didn't just accept what you were told - you made it your own. Keep questioning, keep pushing boundaries. See you tomorrow, rebel.",
    },
  },
  'The Architect': {
    cliff: {
      script: "Let's think systematically here. You can approach this by building on existing frameworks, or by designing something entirely new. Both require careful thought and planning.",
      prompt: "How will you build your understanding?",
      optionA: { label: "Build on frameworks", icon: "🏗️" },
      optionB: { label: "Design fresh", icon: "📐" },
    },
    outro: {
      script: "Excellent work! You've constructed a solid foundation of understanding today. Each piece fits together logically. Tomorrow we'll add another floor to this structure. Well built!",
    },
  },
  'The Diplomat': {
    cliff: {
      script: "There are different perspectives to consider here. Would you like to understand how this affects different people, or focus on finding common ground between viewpoints?",
      prompt: "How will you approach this?",
      optionA: { label: "Explore perspectives", icon: "🤝" },
      optionB: { label: "Find common ground", icon: "🌉" },
    },
    outro: {
      script: "You've done something wonderful today - you've grown your understanding while staying open to different views. That's the heart of wisdom. See you tomorrow for more meaningful exploration!",
    },
  },
  'The Empath': {
    cliff: {
      script: "I can sense you're ready to go deeper. Would you like to explore how this feels on a personal level, or understand how it affects the people around us?",
      prompt: "Where does your heart lead?",
      optionA: { label: "Personal journey", icon: "💭" },
      optionB: { label: "Understanding others", icon: "💞" },
    },
    outro: {
      script: "I'm so proud of the connection you've made with this material today. You didn't just learn it - you felt it. That's what makes learning truly meaningful. Rest well, and I'll see you tomorrow.",
    },
  },
  'The MacGyver': {
    cliff: {
      script: "Okay, here's where it gets practical. Do you want to figure out how to apply this right away, or first understand all the pieces so you can improvise later?",
      prompt: "What's your move?",
      optionA: { label: "Apply it now", icon: "🔧" },
      optionB: { label: "Gather the pieces", icon: "🧰" },
    },
    outro: {
      script: "Now you've got another tool in your toolkit! The best part is you know how to use it. Tomorrow we'll add more skills to your repertoire. Keep tinkering!",
    },
  },
  'The Mystic': {
    cliff: {
      script: "There's more here than meets the eye. Would you like to contemplate the deeper meaning, or see how this connects to the larger patterns of existence?",
      prompt: "Which wisdom calls to you?",
      optionA: { label: "Contemplate deeply", icon: "🧘" },
      optionB: { label: "See the patterns", icon: "✨" },
    },
    outro: {
      script: "The wisdom you've gained today goes beyond facts - it touches something deeper. Carry this insight with you. When we meet again tomorrow, we'll explore even further.",
    },
  },
  'The Provider': {
    cliff: {
      script: "Now let's think about how this helps people. Do you want to focus on how you can use this to help those close to you, or how it could benefit your community?",
      prompt: "Who will you help?",
      optionA: { label: "Help loved ones", icon: "🏠" },
      optionB: { label: "Serve community", icon: "🤲" },
    },
    outro: {
      script: "You've learned something valuable today - something you can share and use to help others. That's the best kind of knowledge. See you tomorrow, and keep caring for those around you!",
    },
  },
  'The Storyteller': {
    cliff: {
      script: "Every good story has a turning point. Do you want to see how this tale unfolds through personal narratives, or explore the bigger story that connects us all?",
      prompt: "Which story draws you in?",
      optionA: { label: "Personal tales", icon: "📖" },
      optionB: { label: "The bigger story", icon: "🌍" },
    },
    outro: {
      script: "And that's today's chapter complete! What a story we've woven together. Every great tale needs a hero who keeps showing up - that's you. See you tomorrow for the next chapter!",
    },
  },
  'The Strategist': {
    cliff: {
      script: "Let's be strategic about this. Do you want to focus on the immediate advantages this knowledge provides, or think about the long-term implications and possibilities?",
      prompt: "What's your strategy?",
      optionA: { label: "Immediate gains", icon: "🎯" },
      optionB: { label: "Long-term vision", icon: "♟️" },
    },
    outro: {
      script: "Strategic move, completing today's lesson! You now have knowledge that others don't - use it wisely. Tomorrow we'll add to your competitive advantage. Well played!",
    },
  },
  'The Survivor': {
    cliff: {
      script: "Here's what matters - this knowledge can help you. Do you want to focus on how it applies to challenges you're facing now, or build resilience for whatever comes next?",
      prompt: "What serves you best?",
      optionA: { label: "Face current challenges", icon: "💪" },
      optionB: { label: "Build for tomorrow", icon: "🛡️" },
    },
    outro: {
      script: "You've added another skill to your survival toolkit today. Every piece of knowledge makes you stronger and more prepared. Keep showing up - you've got this. See you tomorrow!",
    },
  },
};

interface CliffContent {
  script: string;
  prompt: string;
  optionA: { label: string; icon: string };
  optionB: { label: string; icon: string };
}

interface OutroContent {
  script: string;
}

interface CoreLesson {
  id: string;
  day_number: number;
  topic: string;
}

async function getLesson(dayNumber: number): Promise<CoreLesson | null> {
  const { data, error } = await supabase
    .from('core_lessons')
    .select('id, day_number, topic')
    .eq('day_number', dayNumber)
    .single();
  
  if (error) {
    console.error(`❌ Error fetching lesson ${dayNumber}:`, error.message);
    return null;
  }
  return data;
}

async function getExistingAtoms(lessonId: string): Promise<Set<string>> {
  const { data } = await supabase
    .from('lesson_atoms')
    .select('archetype, phase')
    .eq('core_lesson_id', lessonId);
  
  const existing = new Set<string>();
  data?.forEach(a => existing.add(`${a.archetype}|${a.phase}`));
  return existing;
}

async function generateAtomsForDay(dayNumber: number, dryRun: boolean): Promise<{ created: number; skipped: number }> {
  console.log(`\n📅 Processing Day ${dayNumber}...`);
  
  const lesson = await getLesson(dayNumber);
  if (!lesson) {
    console.log(`   ⚠️ No lesson found for Day ${dayNumber}`);
    return { created: 0, skipped: 0 };
  }
  
  console.log(`   📚 Topic: "${lesson.topic}"`);
  
  const existingAtoms = await getExistingAtoms(lesson.id);
  console.log(`   📊 Existing atoms: ${existingAtoms.size}`);
  
  let created = 0;
  let skipped = 0;
  const atomsToInsert: any[] = [];
  
  for (const archetype of ARCHETYPES) {
    const content = ARCHETYPE_CONTENT[archetype];
    if (!content) continue;
    
    // Check Cliff
    const cliffKey = `${archetype}|Cliff`;
    if (!existingAtoms.has(cliffKey)) {
      atomsToInsert.push({
        core_lesson_id: lesson.id,
        archetype,
        phase: 'Cliff',
        content: {
          script: content.cliff.script,
          kellyPose: 'contemplative',
          kellyEmotion: 'thoughtful',
          cliffPrompt: content.cliff.prompt,
          options: [
            {
              letter: 'A',
              text: content.cliff.optionA.label,
              icon: content.cliff.optionA.icon,
              quality: 'good',
              response: "Great choice! Let's explore this path together.",
            },
            {
              letter: 'B', 
              text: content.cliff.optionB.label,
              icon: content.cliff.optionB.icon,
              quality: 'good',
              response: "Excellent decision! This approach will serve you well.",
            },
          ],
        },
      });
      console.log(`   ➕ ${archetype} Cliff`);
    } else {
      skipped++;
    }
    
    // Check Outro
    const outroKey = `${archetype}|Outro`;
    if (!existingAtoms.has(outroKey)) {
      atomsToInsert.push({
        core_lesson_id: lesson.id,
        archetype,
        phase: 'Outro',
        content: {
          script: content.outro.script,
          kellyPose: 'celebratory',
          kellyEmotion: 'warm',
        },
      });
      console.log(`   ➕ ${archetype} Outro`);
    } else {
      skipped++;
    }
  }
  
  if (atomsToInsert.length === 0) {
    console.log(`   ✅ All Cliff/Outro atoms already exist`);
    return { created: 0, skipped };
  }
  
  if (dryRun) {
    console.log(`   🔍 [DRY RUN] Would create ${atomsToInsert.length} atoms`);
    return { created: atomsToInsert.length, skipped };
  }
  
  // Insert atoms
  const { error } = await supabase
    .from('lesson_atoms')
    .insert(atomsToInsert);
  
  if (error) {
    console.error(`   ❌ Error inserting atoms:`, error.message);
    return { created: 0, skipped };
  }
  
  console.log(`   ✅ Created ${atomsToInsert.length} atoms`);
  created = atomsToInsert.length;
  
  return { created, skipped };
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  let dayNumber: number | undefined;
  let allDays = false;
  let dryRun = false;
  
  for (const arg of args) {
    if (arg.startsWith('--day=')) {
      dayNumber = parseInt(arg.split('=')[1]);
    } else if (arg === '--all-days') {
      allDays = true;
    } else if (arg === '--dry-run') {
      dryRun = true;
    } else if (arg === '--help') {
      console.log(`
GENERATE CLIFF AND OUTRO ATOMS

Fills missing Cliff and Outro phase atoms for lessons.

Usage:
  npx tsx scripts/generate-cliff-outro-atoms.ts --day=17
  npx tsx scripts/generate-cliff-outro-atoms.ts --all-days
  npx tsx scripts/generate-cliff-outro-atoms.ts --day=17 --dry-run

Options:
  --day=<number>    Generate for specific day
  --all-days        Generate for all days with lessons
  --dry-run         Show what would be created without inserting
  --help            Show this help
`);
      process.exit(0);
    }
  }
  
  console.log('═'.repeat(60));
  console.log('🔧 CLIFF & OUTRO ATOM GENERATOR');
  console.log('═'.repeat(60));
  
  if (dryRun) {
    console.log('🔍 DRY RUN MODE - No changes will be made');
  }
  
  let totalCreated = 0;
  let totalSkipped = 0;
  
  if (allDays) {
    // Get all lessons
    const { data: lessons } = await supabase
      .from('core_lessons')
      .select('day_number')
      .order('day_number');
    
    for (const lesson of lessons || []) {
      const result = await generateAtomsForDay(lesson.day_number, dryRun);
      totalCreated += result.created;
      totalSkipped += result.skipped;
    }
  } else if (dayNumber !== undefined) {
    const result = await generateAtomsForDay(dayNumber, dryRun);
    totalCreated = result.created;
    totalSkipped = result.skipped;
  } else {
    console.log('⚠️ Please specify --day=<number> or --all-days');
    process.exit(1);
  }
  
  console.log('\n' + '═'.repeat(60));
  console.log('📊 SUMMARY');
  console.log('═'.repeat(60));
  console.log(`   Created: ${totalCreated} atoms`);
  console.log(`   Skipped: ${totalSkipped} (already exist)`);
  console.log('═'.repeat(60));
}

main().catch(error => {
  console.error('❌ Fatal error:', error);
  process.exit(1);
});
