import { NextResponse } from 'next/server'
import { generateLessonVideo, getBaseVideoCoverage, BASE_VIDEOS } from '@/lib/fal-lipsync-client'
import { put } from '@vercel/blob'
import { sql } from '@/lib/db'

/**
 * POST /api/fal/lipsync
 * 
 * Generate a lip-synced video for a specific lesson
 * Uses existing HeyGen base videos + new audio from ElevenLabs
 * 
 * Body: { dayNumber, phase, ageGroup, archetype }
 */
export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { dayNumber, phase, ageGroup, archetype } = body
    
    // Validate inputs
    if (!dayNumber || !phase || !ageGroup || !archetype) {
      return NextResponse.json({
        success: false,
        error: 'Missing required fields: dayNumber, phase, ageGroup, archetype'
      }, { status: 400 })
    }
    
    console.log(`[fal/lipsync] Generating Day ${dayNumber}/${phase} for ${ageGroup}/${archetype}`)
    
    // 1. Get the audio URL from kelly_lesson_assets
    const assets = await sql`
      SELECT audio_url 
      FROM kelly_lesson_assets 
      WHERE day_number = ${dayNumber} 
        AND phase = ${phase}
        AND age_group = ${ageGroup}
        AND archetype = ${archetype}
      LIMIT 1
    `
    
    if (assets.length === 0 || !assets[0].audio_url) {
      return NextResponse.json({
        success: false,
        error: `No audio found for Day ${dayNumber}/${phase}/${ageGroup}/${archetype}`
      }, { status: 404 })
    }
    
    const audioUrl = assets[0].audio_url as string
    console.log(`[fal/lipsync] Audio URL: ${audioUrl}`)
    
    // 2. Map age_group to age category
    const age = ageGroup === 'kid' ? 'kid' : ageGroup === 'senior' ? 'senior' : 'adult'
    
    // 3. Generate lip-synced video using fal.ai
    const result = await generateLessonVideo({
      audioUrl,
      age,
      archetype,
    })
    
    console.log(`[fal/lipsync] fal.ai result:`, result.videoUrl)
    
    // 4. Upload to Vercel Blob for permanent storage
    const videoResponse = await fetch(result.videoUrl)
    const videoBuffer = await videoResponse.arrayBuffer()
    
    const blobPath = `video/kelly/day-${String(dayNumber).padStart(3, '0')}/${phase}-${ageGroup}-${archetype}.mp4`
    const blob = await put(blobPath, videoBuffer, {
      access: 'public',
      contentType: 'video/mp4',
      addRandomSuffix: false,
    })
    
    console.log(`[fal/lipsync] Uploaded to Blob: ${blob.url}`)
    
    // 5. Update database with new video URL
    await sql`
      UPDATE kelly_lesson_assets 
      SET video_url = ${blob.url},
          video_source = 'fal_lipsync',
          status = 'completed',
          updated_at = NOW()
      WHERE day_number = ${dayNumber}
        AND phase = ${phase}
        AND age_group = ${ageGroup}
        AND archetype = ${archetype}
    `
    
    return NextResponse.json({
      success: true,
      dayNumber,
      phase,
      ageGroup,
      archetype,
      videoUrl: blob.url,
      duration: result.duration,
      source: 'fal_lipsync',
    })
    
  } catch (error) {
    console.error('[fal/lipsync] Error:', error)
    return NextResponse.json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 })
  }
}

/**
 * GET /api/fal/lipsync
 * 
 * Returns coverage info for base videos
 */
export async function GET() {
  const coverage = getBaseVideoCoverage()
  
  return NextResponse.json({
    success: true,
    coverage,
    baseVideos: BASE_VIDEOS,
    instructions: [
      '1. Generate more HeyGen base videos for missing age/archetype combos',
      '2. Add their URLs to BASE_VIDEOS in lib/fal-lipsync-client.ts',
      '3. Then any lesson can be generated by: POST /api/fal/lipsync { dayNumber, phase, ageGroup, archetype }',
    ],
  })
}
